package model

import (
	"database/sql"
	"fmt"
)

// --- Константы ---

const (
	OrderStatusPending = "pending"

	EmailNotifyFormat      = "[EMAIL] Уведомление отправлено на %s: %s\n"
	SMSNotifyFormat        = "[SMS] Сообщение отправлено на %s: %s\n"
	TelegramNotifyFormat   = "[TELEGRAM] Уведомление отправлено %s: %s\n"

	OrderCreatedMessage = "Заказ на сумму %.2f успешно создан"

	MainOption1 = "=== Вариант 1: EmailSender ==="
	MainOption2 = "=== Вариант 2: SMSSender ==="
	MainOption3 = "=== Вариант 3: TelegramNotifier ==="
)

// --- Абстракции (интерфейсы) ---

// RepositoryWriter — абстракция для записи данных.
type RepositoryWriter interface {
	CreateOrder(customer string, products []string, total float64) error
}

// RepositoryInitializer — абстракция для инициализации БД.
type RepositoryInitializer interface {
	Initialize() error
}

// Notifier — абстракция для уведомлений.
type Notifier interface {
	Send(to string, message string) error
	Notify(customer string, message string) error
}

// --- Models ---

type Order struct {
	ID       int
	Customer string
	Products string
	Total    float64
	Status   string
}

// --- Low-level реализации ---

type EmailSender struct{}

func NewEmailSender() *EmailSender { return &EmailSender{} }

func (s *EmailSender) Send(to string, message string) error {
	fmt.Printf(EmailNotifyFormat, to, message)
	return nil
}

func (s *EmailSender) Notify(customer string, message string) error {
	return s.Send(customer, message)
}

type SMSSender struct{}

func NewSMSSender() *SMSSender { return &SMSSender{} }

func (s *SMSSender) Send(to string, message string) error {
	fmt.Printf(SMSNotifyFormat, to, message)
	return nil
}

func (s *SMSSender) Notify(customer string, message string) error {
	return s.Send(customer, message)
}

type TelegramNotifier struct{}

func NewTelegramNotifier() *TelegramNotifier { return &TelegramNotifier{} }

func (n *TelegramNotifier) Send(to string, message string) error {
	fmt.Printf(TelegramNotifyFormat, to, message)
	return nil
}

func (n *TelegramNotifier) Notify(customer string, message string) error {
	return n.Send(customer, message)
}

type SQLiteRepository struct{ db *sql.DB }

func NewSQLiteRepository(db *sql.DB) *SQLiteRepository { return &SQLiteRepository{db: db} }

func (r *SQLiteRepository) CreateOrder(customer string, products []string, total float64) error {
	_, err := r.db.Exec(
		"INSERT INTO orders (customer, products, total, status) VALUES (?, ?, ?, ?)",
		customer, fmt.Sprintf("%v", products), total, OrderStatusPending,
	)
	return err
}

func (r *SQLiteRepository) Initialize() error {
	_, err := r.db.Exec(`
	CREATE TABLE IF NOT EXISTS orders (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		customer TEXT NOT NULL,
		products TEXT NOT NULL,
		total REAL NOT NULL,
		status TEXT NOT NULL
	)`)
	return err
}

type PostgreSQLRepository struct{ db *sql.DB }

func NewPostgreSQLRepository(db *sql.DB) *PostgreSQLRepository {
	return &PostgreSQLRepository{db: db}
}

func (r *PostgreSQLRepository) CreateOrder(customer string, products []string, total float64) error {
	_, err := r.db.Exec(
		"INSERT INTO orders (customer, products, total, status) VALUES ($1, $2, $3, $4)",
		customer, fmt.Sprintf("%v", products), total, OrderStatusPending,
	)
	return err
}

func (r *PostgreSQLRepository) Initialize() error {
	_, err := r.db.Exec(`
	CREATE TABLE IF NOT EXISTS orders (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		customer TEXT NOT NULL,
		products TEXT NOT NULL,
		total REAL NOT NULL,
		status TEXT NOT NULL
	)`)
	return err
}
